SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS regions;
DROP TABLE IF EXISTS provinces;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE regions
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(10)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    image VARCHAR(255) NULL
    );

CREATE TABLE provinces
(
    id        INT PRIMARY KEY AUTO_INCREMENT,
    code      VARCHAR(10)  NOT NULL UNIQUE,
    name      VARCHAR(100) NOT NULL,
    region_id INT          NOT NULL,
    FOREIGN KEY (region_id) REFERENCES regions (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
    );