CREATE TABLE IF NOT EXISTS regions
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(10)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    image VARCHAR(255) NULL
    );

CREATE TABLE IF NOT EXISTS provinces
(
    id        INT PRIMARY KEY AUTO_INCREMENT,
    code      VARCHAR(10)  NOT NULL UNIQUE,
    name      VARCHAR(100) NOT NULL,
    region_id INT          NOT NULL,
    FOREIGN KEY (region_id) REFERENCES regions (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
    );